// examples/vue-wrapper/src/App.vue
<script setup lang="ts">
// Virtual modules registered by the bundler plugin.
// zeus:vue:${tag} is the exact virtual module ID.
import { ZButton } from 'zeus:vue:z-button'

function handlePress(event: CustomEvent<{ nativeEvent: MouseEvent }>) {
  console.log('Button pressed!', event.detail.nativeEvent)
}
</script>

<template>
  <div>
    <h1>Zeus Vue Wrapper</h1>

    <div class="demo-section">
      <h3>Default Variant</h3>
      <ZButton @press="handlePress">Default Button</ZButton>
    </div>

    <div class="demo-section">
      <h3>Outline Variant</h3>
      <ZButton variant="outline">Outline Button</ZButton>
    </div>

    <div class="demo-section">
      <h3>Disabled</h3>
      <ZButton disabled>Disabled Button</ZButton>
    </div>
  </div>
</template>

// examples/react-wrapper/src/App.tsx
// Virtual modules are registered by the bundler plugin.
// zeus:react:${tag} is the exact virtual module ID.
// The bundler plugin resolveId hook intercepts these.
import { ZButton } from 'zeus:react:z-button'

export function App() {
  return (
    <div>
      <h1>Zeus React Wrapper</h1>

      <div className="demo-section">
        <h3>Default Variant</h3>
        <ZButton
          onPress={(event: CustomEvent<{ nativeEvent: MouseEvent }>) => {
            event.detail.nativeEvent.preventDefault()
            console.log('Button pressed!')
          }}
        >
          Default Button
        </ZButton>
      </div>

      <div className="demo-section">
        <h3>Outline Variant</h3>
        <ZButton variant="outline">Outline Button</ZButton>
      </div>

      <div className="demo-section">
        <h3>Disabled</h3>
        <ZButton disabled>Disabled Button</ZButton>
      </div>
    </div>
  )
}
